# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

# Fabric API
fabric_version=0.114.0+1.21.1

# Mod Properties
mod_version = 1.0.0
maven_group = net.digitalpear
archives_base_name = armored-wool

modid=armored_wool


#conditional_mixin_version=0.6.4

colorful_books_version=1.4+1.21.4-beta1
cloth_version=15.0.140
modmenu_version=11.0.3